# config.py
LLAMA_SERVER_URL = "http://localhost:8080/v1/chat/completions"

STORY_MODEL = "ggml-org/gemma-3-12b-it-qat-GGUF:Q4_0"
STORY_TEMPERATURE = 0.8
STORY_MAX_TOKENS = 800

TRANSMISSION_MODEL = "ggml-org/gemma-3-12b-it-qat-GGUF:Q4_0"
TRANSMISSION_TEMPERATURE = 0.9
TRANSMISSION_MAX_TOKENS = 200

MAX_HISTORY_MESSAGES = 30
MAX_TOTAL_CHARS = 20000
WORLD_STATE_PATH = "WorldState/worldstate.json"
TICK_UPDATE_INTERVAL = 10